### ISSUE TITLE
[Enhancement] DNS Scripting documentation update

### ISSUE THREAD

**Issue by tobidemski** [webprofusion/certify-docs#26]
Hey guys,

I want to suggest some points to the dns scripting section in your documentation because im currently trying to build a custom script for dns updates / deletes for the netcup host.

"_Its hard to know how the value in the txt record has to be if a apex domain is also included in the request.
Documentation quote: "When an 'apex domain' like example.com is included in the certificate request for a wildcard (e.g. *.example.com) both TXT records will have the same name but different values, so updates need to add to the TXT record values."_"

1. Based on the quote above:  Should both values whitespace separated? Otherwise I dont get it how to store it.
2. The call to the custom delete script isnt shown in the logs or in the sidebar of "Configuration Test Results" (Testing scenario). Its hard to know if the call was triggered (if you are not logging externally) or if you not aware of that the call happens asynchronously. (Found this information in a community thread:  https://community.certifytheweb.com/t/some-feedback-and-questions/313/14)

Effected documentation file: https://github.com/webprofusion/certify-docs/blob/c29344c6024181f9fe8ef2c8a2c5d104191273b3/docs/dns/providers/scripting.md

Would nice to see updates about this two parts in your documentation to makes it a bit more clear for others.

Greetz

**Comment by webprofusion-chrisc** [comment]
Hi, this is a good question, our DNS updates only update a single record at a time, so validation for wildcards needs to be done in multiple steps. The call to the delete is indeed async and we don't wait for it in the UI (some DNS providers take up to a minute to apply changes).
