### ISSUE TITLE
Win7 doesn't have certlm.msc

### ISSUE THREAD

**Issue by rmbolger** [webprofusion/certify-docs#31]
Minor issue with the 202109-letsencrypt.md section regarding the "Windows PCs" section that talks about Win7. It mentions checking `certlm.msc` in the Trusted Root store, but Win7 doesn't appear to have a certlm.msc, only certmgr.msc. You may have to provide a quick instruction on running mmc.exe and adding the snap-in.

Or just running something like this from PowerShell (even 2.0):

```powershell
gci cert:\LocalMachine\Root\CABD2A79A1076A31F21D253635CB039D4329A5E8
```

**Comment by rmbolger** [comment]
Ignore me. I'm seeing things that aren't there. You didn't even reference certlm.msc.

**Comment by webprofusion-chrisc** [comment]
Thanks, I do mention it somewhere else and these docs are constantly changing - here's the doc if you do want to modify anything: https://github.com/webprofusion/certify-docs/blob/master/docs/kb/202109-letsencrypt.md
