### ISSUE TITLE
azure dns validation steps no longer work.

### ISSUE THREAD

**Issue by jwf1776** [webprofusion/certify-docs#7]
$credentials = New-Object Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential gives an error.

**Comment by webprofusion-chrisc** [comment]
Thanks, any particular error?

**Comment by jwf1776** [comment]
It errors on the second command

PS C:\Users\administrator.CRL> $credentials = New-Object Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential -Property @{ StartDate=Get-Date; EndDate=Get-Date -Year 2024; Password=$azurePassword}
New-Object : Cannot find type [Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential]: verify that the
assembly containing this type is loaded.
At line:1 char:16
+ ... edentials = New-Object Microsoft.Azure.Commands.ActiveDirectory.PSADP ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand


Tomorrow I will make some instructions to do it all through the azure web GUI since you have to log in there anyways.

**Comment by webprofusion-chrisc** [comment]
Thanks, much appreciated.

Regarding that command it looks like you need:
`Import-Module Az.Resources`

**Comment by jwf1776** [comment]
As promised some pics of the portal setup for dns authorization… but notice I ran into an issue later in the process and had to revert to http authorization.

Instructions to setup via the azure portal:
•  Sign in to your Azure Account through the Azure portal<https://portal.azure.com>,  Select Azure Active Directory,  Select App registrations,  Select New registration.
Or just go here and do a new registration: (https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps )
-type a name (doesn’t matter) and select the first account type.

[cid:image001.png@01D58F2F.341DC9E0]

3 - Grant the Application rights to update DNS

  *   Login to portal.azure.com from a web browser
  *   Click on your DNS Zone
  *   Click on Access Control (IAM)
  *   Click on (+) Add
  *   Select:
     *   Role: DNS Zone Contributor
     *   Assign access to: Azure AD user, group or application
     *   Select: Type in LetsEcnrypt
     *   Click Save
4 - Create Service Principal Secret
From the Azure portal, click Azure Active Directory:

  *   Click App Registrations
  *   Click LetsEncrypt
  *   Click Certificates & secrets
  *   Click Client secrets
  *   Click New client secret
  *   Type a key description, choose when it will expire (or never – your choice) and click save.
IMPORTANT: The secret is only shown at this point. Copy it as once it’s hidden there is NO way to retrieve it
[cid:image002.png@01D58F30.53151370]

**Comment by webprofusion-chrisc** [comment]
Closing with updated docs #46
